cricket/urls.py
from django.urls import path
from .views import TeamListView, PlayersListView, MatchFixtureView,\
    MatchCreateView, MatchUpdateView, PointTableView


urlpatterns = [
    path('teams/', TeamListView.as_view(), name='team-list'),
    path('matches/', MatchFixtureView.as_view(), name='matches-list'),
    path('points/', PointTableView.as_view(), name='points-table'),
    path('schedulematch/', MatchCreateView.as_view(), name='schedule-match'),
    path('updatematch/<pk>', MatchUpdateView.as_view(), name='update-match'),
    path('teamplayers/<slug>', PlayersListView.as_view(), name='team-details'),
]

main_app/urls.py
"""
url.py of the commgen
"""
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings
from django.urls import path
from django.views.static import serve
# from myapp.views import handler404, handler500, handler403
# from cricket.views import handler404, handler403, handler500
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cricket.urls')),

]

# handler404 = handler404
# handler403 = handler403
# handler500 = handler500

if settings.DEBUG is False:
    # urlpatterns += url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    urlpatterns += url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
else:
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cricket/models.py
"""Summary
"""
from django.db import models


class Team(models.Model):

    """Summary
    
    Attributes:
        club_state (TYPE): Description
        logo_uri (TYPE): Description
        name (TYPE): Description
        slug (TYPE): Description
    """
    
    slug = models.SlugField(max_length=255, unique=True, db_column='cr_team_slug', null=True)
    name = models.CharField(max_length=255, db_column='cr_team_name', unique=True)
    logo_uri = models.CharField(null=True, db_column='cr_team_logo_uri', max_length=255)
    club_state = models.CharField(null=True, db_column='cr_team_club_state', max_length=255)


    def __str__(self):
        """Summary
        
        Returns:
            TYPE: Description
        """
        return self.name

    class Meta:

        """Summary

        Attributes:
            db_table (str): Description
        """

        db_table = 'cr_team_tbl'



class PlayerHistory(models.Model):

    """Summary
    
    Attributes:
        fifties (TYPE): Description
        highest_scores (TYPE): Description
        hundreds (TYPE): Description
        matches (TYPE): Description
        run (TYPE): Description
    """
    
    matches = models.CharField(max_length=255, db_column='cr_player_matches')
    run = models.CharField(max_length=255, db_column='cr_player_run')
    highest_scores = models.CharField(max_length=255, db_column='cr_player_highest_scores')
    fifties = models.CharField(max_length=255, db_column='cr_player_fifties')
    hundreds = models.CharField(max_length=255, db_column='cr_player_hundreds')


    class Meta:

        """Summary
        
        Attributes:
            db_table (str): Description
        """
        
        db_table = 'cr_player_history_tbl'

class Player(models.Model):

    """Summary
    
    Attributes:
        country (TYPE): Description
        firstname (TYPE): Description
        image_uri (TYPE): Description
        jersey_number (TYPE): Description
        lastname (TYPE): Description
        player_history (TYPE): Description
        slug (TYPE): Description
        team (TYPE): Description
    """
    
    slug = models.SlugField(max_length=255, unique=True, db_column='cr_player_slug', null=True)
    firstname = models.CharField(max_length=255, db_column='cr_player_firstname')
    lastname = models.CharField(max_length=255, db_column='cr_player_lastname')
    image_uri = models.CharField(null=True, db_column='cr_player_image_uri', max_length=255)
    jersey_number = models.CharField(db_column='cr_player_jersey_number', max_length=255)
    country = models.CharField(db_column='cr_team_club_state', max_length=255)
    player_history = models.OneToOneField(PlayerHistory, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, db_column='cr_player_team')



    def __str__(self):
        """Summary
        
        Returns:
            TYPE: Description
        """
        return self.firstname + ' ' + self.lastname

    class Meta:

        """Summary
        
        Attributes:
            db_table (str): Description
        """
        
        db_table = 'cr_player_tbl'



class Match(models.Model):

    """Summary
    
    Attributes:
        CHOICES (tuple): Description
        schedule_date (TYPE): Description
        status (TYPE): Description
        team1 (TYPE): Description
        team2 (TYPE): Description
        winner_team (TYPE): Description
    """
    
    CHOICES = (('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Draw', 'Draw'), ('Cancelled', 'Cancelled'))
    team1 = models.ForeignKey(Team, on_delete=models.CASCADE, db_column='cr_match_team1', related_name='match_team1')
    team2 = models.ForeignKey(Team, on_delete=models.CASCADE, db_column='cr_match_team2', related_name='match_team2')
    winner_team = models.ForeignKey(Team, on_delete=models.CASCADE, db_column='cr_match_winner', related_name='cr_match_winner', null=True, blank=True)
    schedule_date = models.DateField(db_column='CG_URM_MODIFICATION_DT', null=True)
    status = models.CharField(choices=CHOICES, db_column='cr_match_status', null=True, max_length=100, default=CHOICES[0][1])



    def __str__(self):
        """Summary
        
        Returns:
            TYPE: Description
        """
        return self.team1.name + ' VS ' + self.team2.name

    class Meta:

        """Summary

        Attributes:
            db_table (str): Description
        """

        db_table = 'cr_match_tbl'

cricket/forms.py
from django import forms
from django.utils.translation import gettext as _
from .models import Match


class MatchForm(forms.ModelForm):
    """Summary
    Last modified by: Bhavya Agrawal, Sprint 25, JIRA card: COM-994, Date: 21apr2020
    """
    def __init__(self, *args, **kwargs):
        super(MatchForm, self).__init__(*args, **kwargs)
        self.fields['team1'].empty_label = None
        self.fields['team2'].empty_label = None
        self.fields['status'].empty_label = None
        self.fields['winner_team'].required = False


    class Meta:
        model = Match
        fields = ('team1', 'team2', 'schedule_date', 'status', 'winner_team')
        widgets = {
            'team1': forms.Select(attrs={'class': 'form-control', 'data-toggle': 'tooltip',
                                         'data-placement': 'right',}),
            'team2': forms.Select(attrs={'class': 'form-control', 'data-toggle': 'tooltip',
                                         'data-placement': 'right',
                                                }),
            'winner_team': forms.Select(attrs={'class': 'form-control', 'data-toggle': 'tooltip',
                                               'data-placement': 'right',
                                                }),
            'status': forms.Select(attrs={'class': 'form-control', 'data-toggle': 'tooltip',
                                          'data-placement': 'right',
                                                }),
            'schedule_date': forms.DateInput(attrs={'class': 'form-control',
                                                    'data-toggle': 'tooltip',
                                                    'data-placement': 'right',
                                                    'placeholder': 'YYYY-MM-DD'
            })

        }

cricket/views.py
"""
    Created by: Bhavya Agrawal
"""


# Django
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse
#Local Django
from .models import Team, Match, Player
from .forms import MatchForm

######################Team Views #######################################
class TeamListView(ListView):

    """Summary

    Attributes:
        queryset (TYPE): Description
        template_name (str): Description
    """

    queryset = Team.objects.all()
    template_name = 'cricket/team_list.html'

###################### Player Views #######################################

class PlayersListView(ListView):

    """Summary

    Attributes:
        queryset (TYPE): Description
        template_name (str): Description
    """

    template_name = 'cricket/player_list.html'
    queryset = Player.objects.all()

    def get_queryset(self):
        """Summary

        Returns:
            TYPE: Description
        """
        return Player.objects.filter(team__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        """Summary

        Args:
            **kwargs: Description

        Returns:
            TYPE: Description
        """
        context = super().get_context_data(**kwargs)
        team_name = Team.objects.get(slug=self.kwargs['slug'])
        context['slug'] = team_name
        return context



###################### Match Views #######################################


class MatchFixtureView(ListView):

    """Summary
    
    Attributes:
        queryset (TYPE): Description
    """
    
    queryset = Match.objects.all()



class MatchCreateView(CreateView):

    """Summary

    Attributes:
        form_class (TYPE): Description
        model (TYPE): Description
    """

    model = Match
    form_class = MatchForm

    def get_success_url(self):
        """Summary

        Returns:
            TYPE: Success url
        """
        return reverse('matches-list')



class MatchUpdateView(UpdateView):

    """Summary

    Attributes:
        form_class (TYPE): Form Class
        model (TYPE): Model class
    """

    model = Match
    form_class = MatchForm

    def get_success_url(self):
        """Summary

        Returns:
            TYPE: Success url
        """

        return reverse('matches-list')



class PointTableView(ListView):

    """Summary

    Attributes:
        queryset (TYPE): Description
        template_name (str): Description
    """

    template_name = 'cricket/point_table.html'

    def get_queryset(self):
        """Summary

        Returns:
            TYPE: object of Team class
        """
        return Team.objects.all()

templates/cricket/match_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}


<div class="container" role="main" style="font-family: arial;">
  <div class="row">
    <div class="col-md-9">
      <h1 style="font-size: 40px;margin-top: 2rem">{% trans 'Schedule Match' %}</h1>
    </div>
  </div>


      <div class="row" style="margin-top:20px">
        {{form.errors}}
      </div>


    <form method="post" 
    class="needs-validation" novalidate  style="margin-top: 4%">
      {% csrf_token %}

      <div class="row" style="margin-top:20px">
       <div class="col-md-2">
        <label for="id_team1" class="col-form-label">{{form.team1.label}}<span style="color: red;">*</span></label>
        </div>

        <div class="col-md-8">
          {{form.team1}}
        </div>
      </div>

      <div class="row" style="margin-top: 30px">
        <div class="col-md-2">
          <label for="id_team2" class="col-form-label">{{form.team2.label}}<span style="color: red;">*</span></label>
        </div>

        <div class="col-md-8">
          {{form.team2}}
        </div> 
      </div>

        <div class="row" style="margin-top:20px">
         <div class="col-md-2">
        <label for="id_schedule_date" class="col-form-label">{{form.schedule_date.label}}</label>
        </div>

        <div class="col-md-8">
          {{form.schedule_date}}
        </div>          
        </div>


       <div class="row" style="margin-top:20px">
         <div class="col-md-2">
        <label for="id_winner_team" class="col-form-label">{{form.winner_team.label}}</label>
        </div>

        <div class="col-md-8">
          {{form.winner_team}}
        </div>          
        </div>


      <div class="row" style="margin-top: 30px">
        <div class="col-md-2">
          <label for="id_team2" class="col-form-label">{{form.status.label}}<span style="color: red;">*</span></label>
        </div>

        <div class="col-md-8">
          {{form.status}}
        </div> 
      </div>

        <div class="row" style="margin-top: .5rem">
        <div class="col-md-8 offset-md-2" style="text-align: right;">
          <span style="color: #000;font-size: 16px"><span style="color: red;">*</span> {% trans 'Mandatory' %}</span>
        </div>
        </div>
        <div class="row" style="margin-top: 3%;">

      <div class="col-md-4 offset-md-8">
        <a href="{% url 'matches-list' %}" class="btn btn-secondary">{% trans 'Cancel' %}</a>
        <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
      </div>
      </div>
    </form>    

</div>

{% endblock  %}

templates/cricket/match_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}


<div class="container" role="main" style="font-family: arial;">

<div class="row">
  <div class="col-md-9">
    
    <h1 style="font-size: 40px;margin-top: 2rem">Matches</h1>
  </div>
</div> 
    <div class="row" style="margin-top: 1rem">
    <div class="col-md-2">
      <a href="{% url 'schedule-match' %}" class="btn btn-warning" style="font-size: 20px;margin-left: 0px;padding: 8px 20px" >
          <i class="glyphicon glyphicon-plus" data-toggle="tooltip" data-placement="top" title="Schedule Match" style="margin-right: 20px"></i>
          Schedule Match</a>
    </div>
  </div>
<table class="table">
  <thead>
    <tr>
      <th scope="col" ><p> </p></th>
      <th scope="col"><p>{% trans 'Match' %}</p></th>
      <th scope="col"><p>{% trans 'Schedule Date' %}</p></th>
      <th scope="col"><p>{% trans 'Winner' %}</p></th>
      <th scope="col"><p>{% trans 'Match Status' %}</p></th>
      <th scope="col"><p></p></th>
      
    </tr>
  </thead>
  <tbody>
    {% for l in object_list %}
    <tr>
      <td style="text-align: left;padding-left: 0rem">{{forloop.counter}}</td>
      <td><a href="{% url 'team-details' l.team1.slug %}"><img src="{{l.team1.logo_uri}}" width="48px" height="48px" style="border: 2px solid black">&nbsp;{{l.team1.name}} </a> &nbsp;&nbsp;<b>VS</b>&nbsp;&nbsp; <a href="{% url 'team-details' l.team2.slug %}"><img src="{{l.team2.logo_uri}}" width="48px" height="48px" style="border: 2px solid black">&nbsp;{{l.team2.name}} </a></td>
      <td>{{l.schedule_date}}</td>
      <td>{{l.winner_team.name}}</td>
      <td>{{l.status}}</td>
      <td><a href="{% url 'update-match' l.pk %}" class="btn btn-primary">Update</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
{% endblock  %}

templates/cricket/player_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}


<div class="container" role="main" style="font-family: arial;">

<div class="row">
  <div class="col-md-9">
    
    <h1 style="font-size: 40px;margin-top: 2rem">{{slug}}</h1>
  </div>
</div> 

<table class="table">
  <thead>
    <tr>
      <th scope="col" ><p> </p></th>
      <th scope="col"><p>{% trans 'First Name' %}</p></th>
      <th scope="col"><p>{% trans 'Last Name' %}</p></th>
      <th scope="col"><p>{% trans 'Matches Played' %}</p></th>
      <th scope="col"><p>{% trans 'Highest Scores' %}</p></th>
      <th scope="col"><p>{% trans 'Country' %}</p></th>
      
    </tr>
  </thead>
  <tbody>
    {% for l in object_list %}
    <tr>
      <td style="text-align: left;padding-left: 0rem"><a href=""><img src="{{l.image_uri}}" width="48px" height="48px" style="border: 2px solid black"> </a></td>
      <td>{{l.firstname}}</td>
      <td>{{l.lastname}}</td>
      <td>{{l.player_history.matches}}</td>
      <td>{{l.player_history.highest_scores}}</td>
      <td>{{l.country}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
{% endblock  %}

templates/cricket/point_table.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}


<div class="container" role="main" style="font-family: arial;">

<div class="row">
  <div class="col-md-9">
    
    <h1 style="font-size: 40px;margin-top: 2rem">{% trans 'Scores' %}</h1>
  </div>
</div> 

<table class="table" id="CM_User_Prfl_tbl">
  <thead>
    <tr>
      <th scope="col" ><p> </p></th>
      <th scope="col"><p>{% trans 'Name' %}</p></th>
      <th scope="col"><p>{% trans 'Points' %}</p></th>
      
    </tr>
  </thead>
  <tbody>
    {% for l in object_list %}
    <tr>
      <td style="text-align: left;padding-left: 0rem"><a href="{% url 'team-details' l.slug %}"><img src="{{l.logo_uri}}" width="48px" height="48px" style="border: 2px solid black"> </a></td>
      <td>{{l.name}}</td>
      <td>{{l.cr_match_winner.count}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
{% endblock  %}

templates/cricket/team_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block content %}


<div class="container" role="main" style="font-family: arial;">

<div class="row">
  <div class="col-md-9">
    
    <h1 style="font-size: 40px;margin-top: 2rem">{% trans 'Teams' %}</h1>
  </div>
</div> 

<table class="table" id="CM_User_Prfl_tbl">
  <thead>
    <tr>
      <th scope="col" ><p> </p></th>
      <th scope="col"><p>{% trans 'Name' %}</p></th>
      <th scope="col"><p>{% trans 'Club State' %}</p></th>
      
    </tr>
  </thead>
  <tbody>
    {% for l in object_list %}
    <tr>
      <td style="text-align: left;padding-left: 0rem"><a href="{% url 'team-details' l.slug %}"><img src="{{l.logo_uri}}" width="48px" height="48px" style="border: 2px solid black"> </a></td>
      <td>{{l.name}}</td>
      <td>{{l.club_state}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

</div>
{% endblock  %}